[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.23"
clap = { version = "4.0.29", features = ["derive"] }
regex = "1.6.0"
reqwest = { version = "0.11.13", features = ["cookies", "blocking"] }
